### ISSUE TITLE
talk- How to use GIT commands

### ISSUE THREAD

**Issue by sanjeevyadavIT** [jslovers/Welcome-to-JSLovers#15]
## Talk Name
GIT 101

## Description
Talk is basically aim at beginners, introducing them about GIT and GIT commands. 
There will be demo of each command.

Talk covers basic git commands

- init
- clone
-  status
-  add
- commit
- log
- remote
- push
- pull
- diff
- reset
- branch
- checkout
- merge
- stash

## Demo slide
http://slides.com/alexakasanjeev/how-to-use-git#/

## Prerequisite
Nothing major

⌛️ Talk Duration - **30 mins**
👤 Name - Sanjeev Yadav
📍 Location - Delhi

**Comment by Neha** [comment]
@alexakasanjeev  Could you please make a small intro video of yourself and topic and share with us on whatsapp 9953193180?

**Comment by sanjeevyadavIT** [comment]
I will make the video, upload on Youtube and share the url, I'm not on Whatsapp (will that work)

**Comment by Neha** [comment]
@alexakasanjeev  will work :)

**Comment by sanjeevyadavIT** [comment]
hi @Neha this is the video: https://youtu.be/QoeXrZss_Qg

Also, I have an open source ecommerce project which uses magento 2 API and react native: https://github.com/alexakasanjeev/magento_react_native if you want I can talk about my project too for 5 mins later when people are showcasing their projects.

**Comment by ashokdey** [comment]
You are in.

**Comment by sanjeevyadavIT** [comment]
Thank you, and whom should I contact in case of queries, and what are the things I need to know before presenting

**Comment by Neha** [comment]
@alexakasanjeev  Can you share 1-2 lines about yourself and social media handles?

**Comment by sanjeevyadavIT** [comment]
Github Handle: @alexakasanjeev 
twitter handle: @alexakasanjeev 

About me,
Hi, My name is Sanjeev Yadav, I work for Mindfire Solutions. Exploring the dark alleys of Javascript with React Native, Contributing to open source from past 6 months and love reading books. :smile:

**Comment by sanjeevyadavIT** [comment]
Talk is done so closing this issue.
