### ISSUE TITLE
talk- making your own Cryptocurrency

### ISSUE THREAD

**Issue by siddhant1** [jslovers/Welcome-to-JSLovers#17]
## Talk Name
How you could have invented your own Cryptocurrency

## Description
In this I will not talk about how to code a Cryptocurrency but how the Cryptocurrency works, what is a Blockchain , a ledger etc

## Prerequisite

⌛️ Talk Duration - **30 mins**
👤 Name - 
📍 Location - Delhi

**Comment by Neha** [comment]
@ashokdey  and @jaswantsandhu  could you please review this? 
I will be bias towards web only. Would be great if you both can share your views.

**Comment by ashokdey** [comment]
@siddhant1 Let us know the role of JavaScript in your talk.

**Comment by ashokdey** [comment]
Will be closing this if @siddhant1 do not respond by 25th October 2019

**Comment by siddhant1** [comment]
Sorry for not being active , there is certainly no role of javascript in this concept , so i think i will be closing this!
