### ISSUE TITLE
talk - So you've got a design spec, what's the next step?

### ISSUE THREAD

**Issue by kamleshchandnani** [jslovers/Welcome-to-JSLovers#20]
## Talk Name
So you've got a design spec, what's the next step?

## Description
Imagine you've got a design spec from a product designer and you're asked to create a component. What would be your first step after that? This talk is mostly focussed on that once we get a requirement then what would be the next step. How as a developer we should think of use cases and derive an API for our components rather than just going ahead and thinking of implementation details. 

**Things covered in talk**
I would take an example of a requirement spec(typically created by a product designer) and refer to it and then try to convert it into a component. I'll get hands-on and do live code so the attendees would be able to relate better that how we should approach a problem and then implement it.

## Prerequisite
* [x] HTML
* [x] JavaScript

⌛️ Talk Duration - **30 mins**
👤 Name - Kamlesh Chandnani
📍 Location - Bangalore

## Social links
[Twitter](https://twitter.com/_kamlesh_)
[GitHub](https://github.com/kamleshchandnani)

**Comment by Neha** [comment]
Hello,

Please share your social media profile

Thanks
Neha

**Comment by kamleshchandnani** [comment]
Hey Neha,
I’ve Updated the info 😊
