### ISSUE TITLE
talk- Design System - from a designer’s point of view.

### ISSUE THREAD

**Issue by bhartibhagtani** [jslovers/Welcome-to-JSLovers#21]
## Talk Name
Design System - from a designer’s point of view.

## Description
So, “design system” is the new cool and a lot of discussion is being heard about the design system in the design community now for the last two years. So, this talk is going to be focused on how creating Design Systems helps solve problems every designer and developer faces while scaling up.

**The talk will have three parts-**

**Why?** which will cover why a design system is needed.
**When?** Which will cover when should a design system be created- the right time.
**How?** Which will cover the tools and approach to create a design system with a small hands on example.

## Prerequisite
Open mind 🙂 

⌛️ Talk Duration - **30 mins**
👤 Name - Bharti Bhagtani
📍 Location - Bangalore 

## Social Media
[Twitter](https://twitter.com/BhagtaniBharti)

**Comment by Neha** [comment]
Hello @bhartibhagtani  ,

Please share your social media links.

Thanks,
Neha
