### ISSUE TITLE
talk- Consumption of React Web Toolkit

### ISSUE THREAD

**Issue by sanyamdogra** [jslovers/Welcome-to-JSLovers#22]
## Talk Name
Consumption of React Web Toolkit

## Description
Starting with the importance of Design System in development, then gradually moving towards consuming the design-react-kit. 
[design-react-kit]( https://github.com/italia/design-react-kit/blob/master/README.EN.md) is an OS project by [Developers Italia](https://developers.italia.it/) community which contains a set of assorted components based on Bootstrap Italia. This org is participating in Hacktoberfest and attendees can contribute to issues labeled as Hacktoberfest.
We will gradually move from the design system to consuming this kit in your react project.
This was my project for the Google Summer of Code 19 and I have worked successfully in completing it. Ref: https://summerofcode.withgoogle.com/projects/#6434052062576640

Things covered in talk

* Design System
* Web Toolkits
* React Web Toolkits and design-react-kit

## Prerequisite
* [*] Beginner level knowledge of React

⌛️ Talk Duration - **20 mins**
👤 Name - Sanyam Dogra 
[Github](https://github.com/sanyamdogra), 
[LinkedIn](https://www.linkedin.com/in/sanyamdogra)
📍 Location - Delhi

**Comment by ashokdey** [comment]
@sanyamdogra thanks for taking interest and coming forward with your talk. Would you be able to present the talk this Saturday? We have [Hacktoberfest 2019](https://www.meetup.com/jslovers/events/265495680/)

**Comment by sanyamdogra** [comment]
Yes that'll be good! @ashokdey
