### ISSUE TITLE
talk- Introduction to Unit & Integration Testing using Jest.js

### ISSUE THREAD

**Issue by sanjeevyadavIT** [jslovers/Welcome-to-JSLovers#23]
## Talk Name
Introduction to Unit & Integration Testing using Jest.js

## Description
Automated testing can help write building a robust application. But many of us thinks testing is hard or time consuming. Would like to give a talk on introduction to testing where Test Driven Development, Unit testing and Integration testing will be covered extensively. 

[Jest.js](https://jestjs.io/) will be used as a testing framework

Things covered in talk
* What is Testing
* Test Driven Development
* Unit Testing with demo using Jest.js
* Integration Testing with demo using Jest.js
* Touch on End-to-End testing

## Slide
http://slides.com/alexakasanjeev/javascript-testing#/

## Prerequisite
* [x] JavaScript

⌛️ Talk Duration - **30 mins**
👤 Name - [Sanjeev Yadav](https://twitter.com/alexakasanjeev)
📍 Location - Delhi

**Comment by ashokdey** [comment]
@alexakasanjeev here is something similar [Unit Testing Node.js](https://github.com/ashokdey/nodejs-unit-testing), so try to make your talk a bit different. Few suggestions:
- Jest vs Mocha
- Jest with React.js App

Also if it's a talk, we have to limit it to 20 mins. 
QAs will be moved to the break/networking time.

**Comment by sanjeevyadavIT** [comment]
ok, I will work and will let you know :)
