### ISSUE TITLE
talk- Performance optimization a success story.

### ISSUE THREAD

**Issue by anand-paragon** [jslovers/Welcome-to-JSLovers#24]
## Talk Name
... Performance optimization a success story.

## Description
... Improving a web app performance by using  CDN, deferring javascript executions, lazy loading images.

Things covered in talk

* CDN (AWS Cloud Front)
* Image lazy loading
* Deferring JavaScript execution
* Lazy loading images.
* Using third party iframes

## Prerequisite
* [x] HTML
* [ ] JavaScript

⌛️ Talk Duration - **30 mins**
👤 Name - Anand Chaudhary
📍 Location - Delhi /Noida

**Comment by Neha** [comment]
Hello,

Could you please add some more content...such as will there be an application on which you will show all these? Will you show a before/after too?

Please add your social media profile too.

Thanks,
Neha

**Comment by ashokdey** [comment]
@anakshiant please ad some technical details like tools you'll be using, some numbers like decrease in bundle size from Y to X and so on.

**Comment by Neha** [comment]
@anakshiant  any update on this?

**Comment by Neha** [comment]
@anakshiant  We have to close this issue as you are not responding. Once you are ready please re-open the issue.
