### ISSUE TITLE
talk- Fundamentals of a design system

### ISSUE THREAD

**Issue by rawris** [jslovers/Welcome-to-JSLovers#25]
## Talk Name
Fundamentals of a design system.

## Description
will be talking about the Design system and the fundamentals of design system. Which includes components, colour palates, typography, font sizes etc and also the need for a design system then I will demonstrate how Design system can be created in React. I will also cover how tools like storybook can be used to create a central isolated repository for all your components (with examples).

Things covered in talk

* Design System Fundamentals
* Design system in React
* Storybook

## Prerequisite
* [ ] HTML
* [ ] JavaScript
* [ ] Basic React

⌛️ Talk Duration - **20 mins**
👤 Name - Rishabh Rawat
[Twitter](https://twitter.com/rishabhrawat48)
[LinkedIn](https://www.linkedin.com/in/rishabh-rawat-27043b126/)
📍 Location - Bangalore (Remote)

**Comment by Neha** [comment]
Hello,

Please review the proposal.  

@jaswantsandhu  we can have him as a remote speaker too for Bangalore.

**Comment by ashokdey** [comment]
@rawris please include the slides for review in 7 to 10 days. The content seems good to me.

**Comment by rawris** [comment]
@ashokdey I will try my best to send you slides ASAP. Thanks
