### ISSUE TITLE
talk- Node Runtime Internal Working

### ISSUE THREAD

**Issue by shubhamqweasd** [jslovers/Welcome-to-JSLovers#29]
## Talk Name
Node.JS Run-time Internal Working

## Description
How NodeJS works internally, asynchronous behavior, V8 bindings in C++,
LibUV working etc.

Things covered in talk

* V8 Basics
* What is an EventLoop and how LibUV works
* How V8 and LibUV are linked.
* How JavaScript is able to perform async stuff.
* Short Demo

## Prerequisite
* ✅  JavaScript
* ✅ Computer Science Fundamentals

⌛️ Talk Duration - **30 mins**
👤 Name - Shubham Aggarwal
📍 Location - Gurgaon

**Comment by Neha** [comment]
Hello @shubhamqweasd ,

Please share the slides.

Thanks,
Neha

**Comment by Neha** [comment]
@shubhamqweasd ,

Please share the slides

Thanks,
Neha
