### ISSUE TITLE
talk-Intro To CI

### ISSUE THREAD

**Issue by rohit-gohri** [jslovers/Welcome-to-JSLovers#32]
## Talk Name

Intro to CI (or How to automate the boring parts?)

## Description

Give a basic introduction about CI and how to go about starting a simple pipeline in Github Actions for a simple ReactJS based Single Page Application (SPA).

#### Things covered in talk

* Need for CI
* Benefits
* Prerequisites
* Different CI/CD Providers
* Walk through of a pipeline
* Demo of changing a pipeline
* Some advanced usages and examples
* Bonus: Deployments using Now

## Prerequisite

* [ ] Basics of NodeJS, npm
* [ ] Basics of what linting, automated tests, builds, etc are
* [ ] Basics of using Github: Pull Requests (PR), Issues, Merge

I have given a smaller version of the talk at my workplace, that can be viewed here: http://github.com/rohit-gohri/slides

⌛️ Talk Duration - **40 mins**
👤 Name - Rohit Gohri
📍 Location - Delhi/NCR

**Comment by ekas** [comment]
Hello @rohit-gohri , Can you please contact me on number 9717029184. So, that we can discuss about your talk for our upcoming meetup.

**Comment by rohit-gohri** [comment]
@ekas I'm out of station this weekend, will be able to contact you on Tuesday. Will that be okay?

**Comment by ekas** [comment]
No worries. We can have a discussion after your come back.

**Comment by ekas** [comment]
Hey @rohit-gohri have you returned.

**Comment by rohit-gohri** [comment]
> Hey @rohit-gohri have you returned.

Hi, Yes. Sorry busy week so far, will call in a short while today

**Comment by Neha** [comment]
Hello Rohit @rohit-gohri 

Would you like to do an online session for this talk again?

Thanks,
Neha

**Comment by rohit-gohri** [comment]
> Would you like to do an online session for this talk again?

Yes. Over something like Zoom?

**Comment by Neha** [comment]
Yes, Google Meet. If yes, please confirm the date (weekends) at hello@jslovers.com

**Comment by rohit-gohri** [comment]
> Yes, Google Meet. If yes, please confirm the date (weekends) at [hello@jslovers.com](mailto:hello@jslovers.com)

Sent a mail

**Comment by ekas** [comment]
This talk is delivered. Hence closing.
