### ISSUE TITLE
talk- Intro to Monorepo & its tools (Lerna)

### ISSUE THREAD

**Issue by mishraa-soumya** [jslovers/Welcome-to-JSLovers#35]
## Talk Name

Intro to Monorepo & its tools

## Description

Starting with the Introduction to the Monorepo architecture and how to manage a mono-repo with Lerna

Things covered in the talk

1.  Need for Mono-repo?
2. Benefits of mono-repo?
3. Use cases of mono-repo?
4. Managing Monorepo using Lerna?
5. Demo 
6. Disadvantages of Mono-repo?

## Prerequisite
* [ ] NPM
* [ ] JavaScript
* [ ] GIT

⌛️ Talk Duration - **30 mins**
👤 Name - Soumya Mishra
📍 Location - Bangalore

**Comment by ekas** [comment]
This talk is delivered. Hence closing.
