### ISSUE TITLE
talk- The tooling aspect of design systems

### ISSUE THREAD

**Issue by itaditya** [jslovers/Welcome-to-JSLovers#6]
## Talk Name
The tooling aspect of design systems

## Description
Companies which are having accelerated growth have started adapting design systems. A design system is a kitchen-sink of all the product decisions, best practices, reusable components and utilities. In this talk I'll cover what tooling can be used to build a robust design system.	

Things I'll cover

* Documenting React components with Styleguidist.
* [Live binding](https://twitter.com/dev__adi/status/1169294660470099969) your design system to an app.
* Performing end-to-end test on your design system.
* Running visual regression test on changes in design system.
* Generating tree-shakable bundle of your design system with Rollup.

## Prerequisite
* [x] React
* [x] Familiar with tools like Jest

⌛️ Talk Duration - **45 mins**
👤 Name - Aditya Agarwal ([Twitter](https://twitter.com/dev__adi))
📍 Location - Bangalore

**Comment by reeversedev** [comment]
This sounds interesting. Excited for this!

**Comment by Neha** [comment]
@itaditya confirmed for November. Congratulation.

**Comment by itaditya** [comment]
That's awesome. Thanks @Neha @reeversedev

**Comment by itaditya** [comment]
@Neha I will not be available on **9th November** and **16th November**. Please schedule my talk accordingly.

**Comment by reeversedev** [comment]
Hey @itaditya I am adding your talk for 24th November as discussed.
